### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by 2013008264** [2013008264/MACloud#6]
### Directory property 기능 만들기. (영대가 하는즁)
* 한 번 Program 이 돌았던 directory 에는 Directory property 를 추가.
* 두 번째 Program 을 돌 때는 Directory property 안에 있는 이미지일 경우, upload 를 하지 않음.
* File naming 은 고민. (.mac.property 로 하였음.)
******************************************************************************
### 지금까지 올린 image 들의 url 이 있는 파일 만들기.
* 다시 다운 받기를 원할 때를 대비하여, 만듬.
* 해당 파일의 확장자는 고민해봐야할 필요가 있음.
* uploaded.(.+) 로 생각중.
******************************************************************************

**Comment by gkrudah** [comment]
근데 저 url들은 어디에 저장할거?

**Comment by 2013008264** [comment]
url uploaded.* {directory_name}.* 에다 저장.

 근데 님 push 안댐 어섬!

**Comment by 2013008264** [comment]
Finished 👍
